# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_vc_schema_created_by import AllOfVcSchemaCreatedBy  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfVcSchemaCreatedBy(unittest.TestCase):
    """AllOfVcSchemaCreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfVcSchemaCreatedBy(self):
        """Test AllOfVcSchemaCreatedBy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_vc_schema_created_by.AllOfVcSchemaCreatedBy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
