# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.groups_api import GroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_controller_connect_did_infos(self):
        """Test case for groups_controller_connect_did_infos

        グループへのDID情報紐付け  # noqa: E501
        """
        pass

    def test_groups_controller_connect_users(self):
        """Test case for groups_controller_connect_users

        グループへのユーザーアカウント紐付け  # noqa: E501
        """
        pass

    def test_groups_controller_connect_vc_infos(self):
        """Test case for groups_controller_connect_vc_infos

        グループへのVC情報紐付け  # noqa: E501
        """
        pass

    def test_groups_controller_connect_vc_schema(self):
        """Test case for groups_controller_connect_vc_schema

        グループへのVCスキーマ紐付け  # noqa: E501
        """
        pass

    def test_groups_controller_connect_vp_infos(self):
        """Test case for groups_controller_connect_vp_infos

        グループへのVP情報紐付け  # noqa: E501
        """
        pass

    def test_groups_controller_create(self):
        """Test case for groups_controller_create

        グループ作成  # noqa: E501
        """
        pass

    def test_groups_controller_disconnect_did_info(self):
        """Test case for groups_controller_disconnect_did_info

        グループのDID情報紐付け解除  # noqa: E501
        """
        pass

    def test_groups_controller_disconnect_user(self):
        """Test case for groups_controller_disconnect_user

        グループのユーザーアカウント紐付け解除  # noqa: E501
        """
        pass

    def test_groups_controller_disconnect_vc_info(self):
        """Test case for groups_controller_disconnect_vc_info

        グループのVC情報紐付け解除  # noqa: E501
        """
        pass

    def test_groups_controller_disconnect_vc_schema(self):
        """Test case for groups_controller_disconnect_vc_schema

        グループのVCスキーマ紐付け解除  # noqa: E501
        """
        pass

    def test_groups_controller_disconnect_vp_info(self):
        """Test case for groups_controller_disconnect_vp_info

        グループのVP情報紐付け解除  # noqa: E501
        """
        pass

    def test_groups_controller_find_all(self):
        """Test case for groups_controller_find_all

        グループ一覧取得  # noqa: E501
        """
        pass

    def test_groups_controller_find_one(self):
        """Test case for groups_controller_find_one

        グループ詳細取得  # noqa: E501
        """
        pass

    def test_groups_controller_remove(self):
        """Test case for groups_controller_remove

        グループ停止  # noqa: E501
        """
        pass

    def test_groups_controller_update(self):
        """Test case for groups_controller_update

        グループ更新  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
