# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vc_infos_api import VcInfosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVcInfosApi(unittest.TestCase):
    """VcInfosApi unit test stubs"""

    def setUp(self):
        self.api = VcInfosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vc_infos_controller_add_label(self):
        """Test case for vc_infos_controller_add_label

        VC情報へのラベル追加  # noqa: E501
        """
        pass

    def test_vc_infos_controller_connect_user(self):
        """Test case for vc_infos_controller_connect_user

        VC情報へのクライアントアカウント紐付け  # noqa: E501
        """
        pass

    def test_vc_infos_controller_create(self):
        """Test case for vc_infos_controller_create

        新規VC発行  # noqa: E501
        """
        pass

    def test_vc_infos_controller_disconnect_user(self):
        """Test case for vc_infos_controller_disconnect_user

        VC情報のクライアントアカウント紐付け解除  # noqa: E501
        """
        pass

    def test_vc_infos_controller_find_all(self):
        """Test case for vc_infos_controller_find_all

        VC情報一覧取得  # noqa: E501
        """
        pass

    def test_vc_infos_controller_find_one(self):
        """Test case for vc_infos_controller_find_one

        VC情報詳細取得  # noqa: E501
        """
        pass

    def test_vc_infos_controller_generate_vp(self):
        """Test case for vc_infos_controller_generate_vp

        新規VP情報生成  # noqa: E501
        """
        pass

    def test_vc_infos_controller_issue(self):
        """Test case for vc_infos_controller_issue

        新規VC発行(スキーマなし)  # noqa: E501
        """
        pass

    def test_vc_infos_controller_upload(self):
        """Test case for vc_infos_controller_upload

        新規VCアップロード  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
