# coding: utf-8

# flake8: noqa

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.auth_api import AuthApi
from swagger_client.api.badges_api import BadgesApi
from swagger_client.api.did_infos_api import DidInfosApi
from swagger_client.api.files_api import FilesApi
from swagger_client.api.groups_api import GroupsApi
from swagger_client.api.health_api import HealthApi
from swagger_client.api.mails_api import MailsApi
from swagger_client.api.settings_api import SettingsApi
from swagger_client.api.users_api import UsersApi
from swagger_client.api.vc_infos_api import VcInfosApi
from swagger_client.api.vc_schemas_api import VcSchemasApi
from swagger_client.api.verifications_api import VerificationsApi
from swagger_client.api.vp_infos_api import VpInfosApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.add_label_to_badge_dto import AddLabelToBadgeDto
from swagger_client.models.add_label_to_did_info_dto import AddLabelToDidInfoDto
from swagger_client.models.add_label_to_vc_info_dto import AddLabelToVcInfoDto
from swagger_client.models.add_label_to_vp_info_dto import AddLabelToVpInfoDto
from swagger_client.models.all_of_badge_response_dto_vc_info import AllOfBadgeResponseDtoVcInfo
from swagger_client.models.all_of_badge_response_dto_vc_schema import AllOfBadgeResponseDtoVcSchema
from swagger_client.models.all_of_badge_vc_info import AllOfBadgeVcInfo
from swagger_client.models.all_of_badge_vc_schema import AllOfBadgeVcSchema
from swagger_client.models.all_of_did_info_created_by import AllOfDidInfoCreatedBy
from swagger_client.models.all_of_did_info_response_dto_did_info import AllOfDidInfoResponseDtoDidInfo
from swagger_client.models.all_of_did_info_user import AllOfDidInfoUser
from swagger_client.models.all_of_did_info_vp_infos import AllOfDidInfoVpInfos
from swagger_client.models.all_of_file_created_by import AllOfFileCreatedBy
from swagger_client.models.all_of_file_response_dto_created_by import AllOfFileResponseDtoCreatedBy
from swagger_client.models.all_of_file_vc_schema import AllOfFileVcSchema
from swagger_client.models.all_of_group_created_by import AllOfGroupCreatedBy
from swagger_client.models.all_of_group_response_dto_created_by import AllOfGroupResponseDtoCreatedBy
from swagger_client.models.all_of_user_created_by import AllOfUserCreatedBy
from swagger_client.models.all_of_user_response_dto_created_by import AllOfUserResponseDtoCreatedBy
from swagger_client.models.all_of_vc_context_vc_schema import AllOfVcContextVcSchema
from swagger_client.models.all_of_vc_info_badge import AllOfVcInfoBadge
from swagger_client.models.all_of_vc_info_created_by import AllOfVcInfoCreatedBy
from swagger_client.models.all_of_vc_info_response_dto_vc_info import AllOfVcInfoResponseDtoVcInfo
from swagger_client.models.all_of_vc_info_user import AllOfVcInfoUser
from swagger_client.models.all_of_vc_info_vc_schema import AllOfVcInfoVcSchema
from swagger_client.models.all_of_vc_schema_created_by import AllOfVcSchemaCreatedBy
from swagger_client.models.all_of_vc_schema_file import AllOfVcSchemaFile
from swagger_client.models.all_of_vc_schema_property_vc_schema import AllOfVcSchemaPropertyVcSchema
from swagger_client.models.all_of_vc_schema_response_dto_created_by import AllOfVcSchemaResponseDtoCreatedBy
from swagger_client.models.all_of_vc_schema_response_dto_file import AllOfVcSchemaResponseDtoFile
from swagger_client.models.all_of_verification_created_by import AllOfVerificationCreatedBy
from swagger_client.models.all_of_verification_response_dto_created_by import AllOfVerificationResponseDtoCreatedBy
from swagger_client.models.all_of_verification_response_dto_vc_info import AllOfVerificationResponseDtoVcInfo
from swagger_client.models.all_of_verification_response_dto_vp_info import AllOfVerificationResponseDtoVpInfo
from swagger_client.models.all_of_verification_vc_info import AllOfVerificationVcInfo
from swagger_client.models.all_of_verification_vp_info import AllOfVerificationVpInfo
from swagger_client.models.all_of_verifications_response_dto_links import AllOfVerificationsResponseDtoLinks
from swagger_client.models.all_of_verifications_response_dto_meta import AllOfVerificationsResponseDtoMeta
from swagger_client.models.all_of_vp_info_created_by import AllOfVpInfoCreatedBy
from swagger_client.models.all_of_vp_info_detail_dto_vp_info import AllOfVpInfoDetailDtoVpInfo
from swagger_client.models.all_of_vp_info_did_info import AllOfVpInfoDidInfo
from swagger_client.models.all_of_vp_info_user import AllOfVpInfoUser
from swagger_client.models.badge import Badge
from swagger_client.models.badge_response_dto import BadgeResponseDto
from swagger_client.models.badges_file_body import BadgesFileBody
from swagger_client.models.badges_response_dto import BadgesResponseDto
from swagger_client.models.connect_did_infos_dto import ConnectDidInfosDto
from swagger_client.models.connect_users_dto import ConnectUsersDto
from swagger_client.models.connect_vc_infos_dto import ConnectVcInfosDto
from swagger_client.models.connect_vc_schemas_dto import ConnectVcSchemasDto
from swagger_client.models.connect_vp_infos_dto import ConnectVpInfosDto
from swagger_client.models.create_badge_dto import CreateBadgeDto
from swagger_client.models.create_did_dto import CreateDidDto
from swagger_client.models.create_group_dto import CreateGroupDto
from swagger_client.models.create_user_dto import CreateUserDto
from swagger_client.models.create_vc_info_dto import CreateVcInfoDto
from swagger_client.models.create_vc_schema_dto import CreateVcSchemaDto
from swagger_client.models.create_vp_info_dto import CreateVpInfoDto
from swagger_client.models.did_info import DidInfo
from swagger_client.models.did_info_response_dto import DidInfoResponseDto
from swagger_client.models.did_infos_response_dto import DidInfosResponseDto
from swagger_client.models.file import File
from swagger_client.models.file_response_dto import FileResponseDto
from swagger_client.models.files_response_dto import FilesResponseDto
from swagger_client.models.generate_did_dto import GenerateDidDto
from swagger_client.models.generate_vp_dto import GenerateVpDto
from swagger_client.models.get_profile_response_dto import GetProfileResponseDto
from swagger_client.models.group import Group
from swagger_client.models.group_response_dto import GroupResponseDto
from swagger_client.models.groups_response_dto import GroupsResponseDto
from swagger_client.models.issue_vc_info_dto import IssueVcInfoDto
from swagger_client.models.link_dto import LinkDto
from swagger_client.models.mail import Mail
from swagger_client.models.mails_response_dto import MailsResponseDto
from swagger_client.models.meta_dto import MetaDto
from swagger_client.models.register_did_dto import RegisterDidDto
from swagger_client.models.registration_process_dto import RegistrationProcessDto
from swagger_client.models.resolve_did_dto import ResolveDidDto
from swagger_client.models.resolve_did_response_dto import ResolveDidResponseDto
from swagger_client.models.send_mail_batch_dto import SendMailBatchDto
from swagger_client.models.send_mail_dto import SendMailDto
from swagger_client.models.setting import Setting
from swagger_client.models.setting_list_response_dto import SettingListResponseDto
from swagger_client.models.setting_response_dto import SettingResponseDto
from swagger_client.models.sign_in_dto import SignInDto
from swagger_client.models.sign_in_response_dto import SignInResponseDto
from swagger_client.models.update_vc_info_dto import UpdateVcInfoDto
from swagger_client.models.update_vc_schema_dto import UpdateVcSchemaDto
from swagger_client.models.upload_vc_dto import UploadVCDto
from swagger_client.models.upload_vp_dto import UploadVPDto
from swagger_client.models.user import User
from swagger_client.models.user_response_dto import UserResponseDto
from swagger_client.models.user_token import UserToken
from swagger_client.models.users_response_dto import UsersResponseDto
from swagger_client.models.v1_files_body import V1FilesBody
from swagger_client.models.vc_context import VcContext
from swagger_client.models.vc_info import VcInfo
from swagger_client.models.vc_info_response_dto import VcInfoResponseDto
from swagger_client.models.vc_infos_response_dto import VcInfosResponseDto
from swagger_client.models.vc_schema import VcSchema
from swagger_client.models.vc_schema_property import VcSchemaProperty
from swagger_client.models.vc_schema_response_dto import VcSchemaResponseDto
from swagger_client.models.vc_schemas_response_dto import VcSchemasResponseDto
from swagger_client.models.verification import Verification
from swagger_client.models.verification_dto import VerificationDto
from swagger_client.models.verification_response_dto import VerificationResponseDto
from swagger_client.models.verifications_response_dto import VerificationsResponseDto
from swagger_client.models.verifiy_badge_file_reponse_dto import VerifiyBadgeFileReponseDto
from swagger_client.models.verifiy_badge_reponse_dto import VerifiyBadgeReponseDto
from swagger_client.models.verify_badge_dto import VerifyBadgeDto
from swagger_client.models.vp_info import VpInfo
from swagger_client.models.vp_info_detail_dto import VpInfoDetailDto
from swagger_client.models.vp_info_response_dto import VpInfoResponseDto
