# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class File(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'filename': 'str',
        'originalname': 'str',
        'type': 'str',
        'file_data': 'str',
        'executed': 'bool',
        'status': 'float',
        'group': 'list[Group]',
        'vc_schema': 'AllOfFileVcSchema',
        'created_by': 'AllOfFileCreatedBy',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'filename': 'filename',
        'originalname': 'originalname',
        'type': 'type',
        'file_data': 'fileData',
        'executed': 'executed',
        'status': 'status',
        'group': 'group',
        'vc_schema': 'vcSchema',
        'created_by': 'createdBy',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, id=None, filename=None, originalname=None, type=None, file_data=None, executed=None, status=None, group=None, vc_schema=None, created_by=None, created_at=None, updated_at=None):  # noqa: E501
        """File - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._filename = None
        self._originalname = None
        self._type = None
        self._file_data = None
        self._executed = None
        self._status = None
        self._group = None
        self._vc_schema = None
        self._created_by = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        self.id = id
        self.filename = filename
        self.originalname = originalname
        self.type = type
        self.file_data = file_data
        self.executed = executed
        self.status = status
        self.group = group
        if vc_schema is not None:
            self.vc_schema = vc_schema
        self.created_by = created_by
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this File.  # noqa: E501

        (必須) ファイルの識別子  # noqa: E501

        :return: The id of this File.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this File.

        (必須) ファイルの識別子  # noqa: E501

        :param id: The id of this File.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def filename(self):
        """Gets the filename of this File.  # noqa: E501

        (任意) システム内で管理される際にシステムによって名付けられるユニークなファイル名  # noqa: E501

        :return: The filename of this File.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this File.

        (任意) システム内で管理される際にシステムによって名付けられるユニークなファイル名  # noqa: E501

        :param filename: The filename of this File.  # noqa: E501
        :type: str
        """
        if filename is None:
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def originalname(self):
        """Gets the originalname of this File.  # noqa: E501

        (必須) システムへアップロード時の元のファイル名  # noqa: E501

        :return: The originalname of this File.  # noqa: E501
        :rtype: str
        """
        return self._originalname

    @originalname.setter
    def originalname(self, originalname):
        """Sets the originalname of this File.

        (必須) システムへアップロード時の元のファイル名  # noqa: E501

        :param originalname: The originalname of this File.  # noqa: E501
        :type: str
        """
        if originalname is None:
            raise ValueError("Invalid value for `originalname`, must not be `None`")  # noqa: E501

        self._originalname = originalname

    @property
    def type(self):
        """Gets the type of this File.  # noqa: E501

        (必須) ファイル形式  # noqa: E501

        :return: The type of this File.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this File.

        (必須) ファイル形式  # noqa: E501

        :param type: The type of this File.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def file_data(self):
        """Gets the file_data of this File.  # noqa: E501

        (必須) ファイルのバイナリデータ  # noqa: E501

        :return: The file_data of this File.  # noqa: E501
        :rtype: str
        """
        return self._file_data

    @file_data.setter
    def file_data(self, file_data):
        """Sets the file_data of this File.

        (必須) ファイルのバイナリデータ  # noqa: E501

        :param file_data: The file_data of this File.  # noqa: E501
        :type: str
        """
        if file_data is None:
            raise ValueError("Invalid value for `file_data`, must not be `None`")  # noqa: E501

        self._file_data = file_data

    @property
    def executed(self):
        """Gets the executed of this File.  # noqa: E501

        (任意) ファイルがCSVの場合、アカウントデータ生成実行に使用されたか。(true: 実行済み, false: 未使用)  # noqa: E501

        :return: The executed of this File.  # noqa: E501
        :rtype: bool
        """
        return self._executed

    @executed.setter
    def executed(self, executed):
        """Sets the executed of this File.

        (任意) ファイルがCSVの場合、アカウントデータ生成実行に使用されたか。(true: 実行済み, false: 未使用)  # noqa: E501

        :param executed: The executed of this File.  # noqa: E501
        :type: bool
        """
        if executed is None:
            raise ValueError("Invalid value for `executed`, must not be `None`")  # noqa: E501

        self._executed = executed

    @property
    def status(self):
        """Gets the status of this File.  # noqa: E501

        (必須) ファイルのステータス  # noqa: E501

        :return: The status of this File.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this File.

        (必須) ファイルのステータス  # noqa: E501

        :param status: The status of this File.  # noqa: E501
        :type: float
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def group(self):
        """Gets the group of this File.  # noqa: E501

        (任意) ファイルを紐づけたグループの配列  # noqa: E501

        :return: The group of this File.  # noqa: E501
        :rtype: list[Group]
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this File.

        (任意) ファイルを紐づけたグループの配列  # noqa: E501

        :param group: The group of this File.  # noqa: E501
        :type: list[Group]
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    @property
    def vc_schema(self):
        """Gets the vc_schema of this File.  # noqa: E501

        (任意) ファイルに紐づいたVCスキーマ  # noqa: E501

        :return: The vc_schema of this File.  # noqa: E501
        :rtype: AllOfFileVcSchema
        """
        return self._vc_schema

    @vc_schema.setter
    def vc_schema(self, vc_schema):
        """Sets the vc_schema of this File.

        (任意) ファイルに紐づいたVCスキーマ  # noqa: E501

        :param vc_schema: The vc_schema of this File.  # noqa: E501
        :type: AllOfFileVcSchema
        """

        self._vc_schema = vc_schema

    @property
    def created_by(self):
        """Gets the created_by of this File.  # noqa: E501

        (必須) ファイルをアップロードしたユーザーアカウント。  # noqa: E501

        :return: The created_by of this File.  # noqa: E501
        :rtype: AllOfFileCreatedBy
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this File.

        (必須) ファイルをアップロードしたユーザーアカウント。  # noqa: E501

        :param created_by: The created_by of this File.  # noqa: E501
        :type: AllOfFileCreatedBy
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def created_at(self):
        """Gets the created_at of this File.  # noqa: E501

        (必須) ファイルの作成日時  # noqa: E501

        :return: The created_at of this File.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this File.

        (必須) ファイルの作成日時  # noqa: E501

        :param created_at: The created_at of this File.  # noqa: E501
        :type: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this File.  # noqa: E501

        (必須) グループの最終更新日時  # noqa: E501

        :return: The updated_at of this File.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this File.

        (必須) グループの最終更新日時  # noqa: E501

        :param updated_at: The updated_at of this File.  # noqa: E501
        :type: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(File, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, File):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
