# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenerateDidDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'did_method': 'list[str]',
        'label': 'str',
        'domain_name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'did_method': 'didMethod',
        'label': 'label',
        'domain_name': 'domainName',
        'description': 'description'
    }

    def __init__(self, did_method=None, label=None, domain_name=None, description=None):  # noqa: E501
        """GenerateDidDto - a model defined in Swagger"""  # noqa: E501
        self._did_method = None
        self._label = None
        self._domain_name = None
        self._description = None
        self.discriminator = None
        self.did_method = did_method
        if label is not None:
            self.label = label
        if domain_name is not None:
            self.domain_name = domain_name
        if description is not None:
            self.description = description

    @property
    def did_method(self):
        """Gets the did_method of this GenerateDidDto.  # noqa: E501

        (必須) 新規生成するDIDのメソッド。(現在対応するDIDメソッド: \"key\", \"ether\", \"ethr:sepolia\", \"ethr:arbitrum:goerli\", \"web\")  # noqa: E501

        :return: The did_method of this GenerateDidDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._did_method

    @did_method.setter
    def did_method(self, did_method):
        """Sets the did_method of this GenerateDidDto.

        (必須) 新規生成するDIDのメソッド。(現在対応するDIDメソッド: \"key\", \"ether\", \"ethr:sepolia\", \"ethr:arbitrum:goerli\", \"web\")  # noqa: E501

        :param did_method: The did_method of this GenerateDidDto.  # noqa: E501
        :type: list[str]
        """
        if did_method is None:
            raise ValueError("Invalid value for `did_method`, must not be `None`")  # noqa: E501
        allowed_values = ["key", "web", "ethr:sepolia", "ethr", "ethr:arbitrum:goerli"]  # noqa: E501
        if not set(did_method).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `did_method` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(did_method) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._did_method = did_method

    @property
    def label(self):
        """Gets the label of this GenerateDidDto.  # noqa: E501

        (任意) DIDの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: did-for-project1)  # noqa: E501

        :return: The label of this GenerateDidDto.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this GenerateDidDto.

        (任意) DIDの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: did-for-project1)  # noqa: E501

        :param label: The label of this GenerateDidDto.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def domain_name(self):
        """Gets the domain_name of this GenerateDidDto.  # noqa: E501

        (任意) did:webメソッドでDIDを生成する際に必要なドメイン名。DIDによって指定されたドメインがドメインネームシステム(DNS)を通じて解決されるときのホスト名。did:webメソッド以外では必要のないパラメータなため任意の項目である。  # noqa: E501

        :return: The domain_name of this GenerateDidDto.  # noqa: E501
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name):
        """Sets the domain_name of this GenerateDidDto.

        (任意) did:webメソッドでDIDを生成する際に必要なドメイン名。DIDによって指定されたドメインがドメインネームシステム(DNS)を通じて解決されるときのホスト名。did:webメソッド以外では必要のないパラメータなため任意の項目である。  # noqa: E501

        :param domain_name: The domain_name of this GenerateDidDto.  # noqa: E501
        :type: str
        """

        self._domain_name = domain_name

    @property
    def description(self):
        """Gets the description of this GenerateDidDto.  # noqa: E501

        (任意) DIDの生成目的や用途など任意で設定可能な説明文。  # noqa: E501

        :return: The description of this GenerateDidDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GenerateDidDto.

        (任意) DIDの生成目的や用途など任意で設定可能な説明文。  # noqa: E501

        :param description: The description of this GenerateDidDto.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerateDidDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerateDidDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
