# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupResponseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'status': 'str',
        'description': 'str',
        'users': 'list[User]',
        'created_by': 'AllOfGroupResponseDtoCreatedBy',
        'did_infos': 'list[DidInfo]',
        'vc_infos': 'list[VcInfo]',
        'vp_infos': 'list[VpInfo]',
        'vc_schemas': 'list[VcSchema]',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'status': 'status',
        'description': 'description',
        'users': 'users',
        'created_by': 'createdBy',
        'did_infos': 'didInfos',
        'vc_infos': 'vcInfos',
        'vp_infos': 'vpInfos',
        'vc_schemas': 'vcSchemas',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, id=None, name=None, status=None, description=None, users=None, created_by=None, did_infos=None, vc_infos=None, vp_infos=None, vc_schemas=None, created_at=None, updated_at=None):  # noqa: E501
        """GroupResponseDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._status = None
        self._description = None
        self._users = None
        self._created_by = None
        self._did_infos = None
        self._vc_infos = None
        self._vp_infos = None
        self._vc_schemas = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.status = status
        self.description = description
        self.users = users
        self.created_by = created_by
        self.did_infos = did_infos
        self.vc_infos = vc_infos
        self.vp_infos = vp_infos
        self.vc_schemas = vc_schemas
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this GroupResponseDto.  # noqa: E501

        グループの識別子  # noqa: E501

        :return: The id of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GroupResponseDto.

        グループの識別子  # noqa: E501

        :param id: The id of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this GroupResponseDto.  # noqa: E501

         グループの名前  # noqa: E501

        :return: The name of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GroupResponseDto.

         グループの名前  # noqa: E501

        :param name: The name of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def status(self):
        """Gets the status of this GroupResponseDto.  # noqa: E501

        グループの状態(1: アクティブ, 0: 停止中)  # noqa: E501

        :return: The status of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GroupResponseDto.

        グループの状態(1: アクティブ, 0: 停止中)  # noqa: E501

        :param status: The status of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["active", "deactive"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def description(self):
        """Gets the description of this GroupResponseDto.  # noqa: E501

        グループの作成目的や用途など任意で設定可能な説明文  # noqa: E501

        :return: The description of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GroupResponseDto.

        グループの作成目的や用途など任意で設定可能な説明文  # noqa: E501

        :param description: The description of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def users(self):
        """Gets the users of this GroupResponseDto.  # noqa: E501

        グループに紐付いたユーザーアカウントの配列  # noqa: E501

        :return: The users of this GroupResponseDto.  # noqa: E501
        :rtype: list[User]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this GroupResponseDto.

        グループに紐付いたユーザーアカウントの配列  # noqa: E501

        :param users: The users of this GroupResponseDto.  # noqa: E501
        :type: list[User]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    @property
    def created_by(self):
        """Gets the created_by of this GroupResponseDto.  # noqa: E501

        グループを作成したユーザーアカウント  # noqa: E501

        :return: The created_by of this GroupResponseDto.  # noqa: E501
        :rtype: AllOfGroupResponseDtoCreatedBy
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this GroupResponseDto.

        グループを作成したユーザーアカウント  # noqa: E501

        :param created_by: The created_by of this GroupResponseDto.  # noqa: E501
        :type: AllOfGroupResponseDtoCreatedBy
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def did_infos(self):
        """Gets the did_infos of this GroupResponseDto.  # noqa: E501

        グループに紐付いたVC情報の配列  # noqa: E501

        :return: The did_infos of this GroupResponseDto.  # noqa: E501
        :rtype: list[DidInfo]
        """
        return self._did_infos

    @did_infos.setter
    def did_infos(self, did_infos):
        """Sets the did_infos of this GroupResponseDto.

        グループに紐付いたVC情報の配列  # noqa: E501

        :param did_infos: The did_infos of this GroupResponseDto.  # noqa: E501
        :type: list[DidInfo]
        """
        if did_infos is None:
            raise ValueError("Invalid value for `did_infos`, must not be `None`")  # noqa: E501

        self._did_infos = did_infos

    @property
    def vc_infos(self):
        """Gets the vc_infos of this GroupResponseDto.  # noqa: E501

        グループに紐付いたVC情報の配列  # noqa: E501

        :return: The vc_infos of this GroupResponseDto.  # noqa: E501
        :rtype: list[VcInfo]
        """
        return self._vc_infos

    @vc_infos.setter
    def vc_infos(self, vc_infos):
        """Sets the vc_infos of this GroupResponseDto.

        グループに紐付いたVC情報の配列  # noqa: E501

        :param vc_infos: The vc_infos of this GroupResponseDto.  # noqa: E501
        :type: list[VcInfo]
        """
        if vc_infos is None:
            raise ValueError("Invalid value for `vc_infos`, must not be `None`")  # noqa: E501

        self._vc_infos = vc_infos

    @property
    def vp_infos(self):
        """Gets the vp_infos of this GroupResponseDto.  # noqa: E501

        グループに紐付いたVP情報の配列  # noqa: E501

        :return: The vp_infos of this GroupResponseDto.  # noqa: E501
        :rtype: list[VpInfo]
        """
        return self._vp_infos

    @vp_infos.setter
    def vp_infos(self, vp_infos):
        """Sets the vp_infos of this GroupResponseDto.

        グループに紐付いたVP情報の配列  # noqa: E501

        :param vp_infos: The vp_infos of this GroupResponseDto.  # noqa: E501
        :type: list[VpInfo]
        """
        if vp_infos is None:
            raise ValueError("Invalid value for `vp_infos`, must not be `None`")  # noqa: E501

        self._vp_infos = vp_infos

    @property
    def vc_schemas(self):
        """Gets the vc_schemas of this GroupResponseDto.  # noqa: E501

        グループに紐付いたVCスキーマの配列  # noqa: E501

        :return: The vc_schemas of this GroupResponseDto.  # noqa: E501
        :rtype: list[VcSchema]
        """
        return self._vc_schemas

    @vc_schemas.setter
    def vc_schemas(self, vc_schemas):
        """Sets the vc_schemas of this GroupResponseDto.

        グループに紐付いたVCスキーマの配列  # noqa: E501

        :param vc_schemas: The vc_schemas of this GroupResponseDto.  # noqa: E501
        :type: list[VcSchema]
        """
        if vc_schemas is None:
            raise ValueError("Invalid value for `vc_schemas`, must not be `None`")  # noqa: E501

        self._vc_schemas = vc_schemas

    @property
    def created_at(self):
        """Gets the created_at of this GroupResponseDto.  # noqa: E501

        グループの作成日時  # noqa: E501

        :return: The created_at of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this GroupResponseDto.

        グループの作成日時  # noqa: E501

        :param created_at: The created_at of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this GroupResponseDto.  # noqa: E501

        グループの最終更新日時  # noqa: E501

        :return: The updated_at of this GroupResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this GroupResponseDto.

        グループの最終更新日時  # noqa: E501

        :param updated_at: The updated_at of this GroupResponseDto.  # noqa: E501
        :type: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupResponseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
