# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VcSchemaProperty(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'prop_index': 'float',
        'prop_name': 'str',
        'prop_type': 'str',
        'parent_object_index': 'float',
        'vc_schema': 'AllOfVcSchemaPropertyVcSchema',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'prop_index': 'propIndex',
        'prop_name': 'propName',
        'prop_type': 'propType',
        'parent_object_index': 'parentObjectIndex',
        'vc_schema': 'vcSchema',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, id=None, prop_index=None, prop_name=None, prop_type=None, parent_object_index=None, vc_schema=None, created_at=None, updated_at=None):  # noqa: E501
        """VcSchemaProperty - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._prop_index = None
        self._prop_name = None
        self._prop_type = None
        self._parent_object_index = None
        self._vc_schema = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        self.id = id
        self.prop_index = prop_index
        self.prop_name = prop_name
        self.prop_type = prop_type
        self.parent_object_index = parent_object_index
        if vc_schema is not None:
            self.vc_schema = vc_schema
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this VcSchemaProperty.  # noqa: E501

        The ID of the vcSchema  # noqa: E501

        :return: The id of this VcSchemaProperty.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VcSchemaProperty.

        The ID of the vcSchema  # noqa: E501

        :param id: The id of this VcSchemaProperty.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def prop_index(self):
        """Gets the prop_index of this VcSchemaProperty.  # noqa: E501

        property Index number  # noqa: E501

        :return: The prop_index of this VcSchemaProperty.  # noqa: E501
        :rtype: float
        """
        return self._prop_index

    @prop_index.setter
    def prop_index(self, prop_index):
        """Sets the prop_index of this VcSchemaProperty.

        property Index number  # noqa: E501

        :param prop_index: The prop_index of this VcSchemaProperty.  # noqa: E501
        :type: float
        """
        if prop_index is None:
            raise ValueError("Invalid value for `prop_index`, must not be `None`")  # noqa: E501

        self._prop_index = prop_index

    @property
    def prop_name(self):
        """Gets the prop_name of this VcSchemaProperty.  # noqa: E501

        property Name of credentialSubject  # noqa: E501

        :return: The prop_name of this VcSchemaProperty.  # noqa: E501
        :rtype: str
        """
        return self._prop_name

    @prop_name.setter
    def prop_name(self, prop_name):
        """Sets the prop_name of this VcSchemaProperty.

        property Name of credentialSubject  # noqa: E501

        :param prop_name: The prop_name of this VcSchemaProperty.  # noqa: E501
        :type: str
        """
        if prop_name is None:
            raise ValueError("Invalid value for `prop_name`, must not be `None`")  # noqa: E501

        self._prop_name = prop_name

    @property
    def prop_type(self):
        """Gets the prop_type of this VcSchemaProperty.  # noqa: E501

        property Type of credentialSubject  # noqa: E501

        :return: The prop_type of this VcSchemaProperty.  # noqa: E501
        :rtype: str
        """
        return self._prop_type

    @prop_type.setter
    def prop_type(self, prop_type):
        """Sets the prop_type of this VcSchemaProperty.

        property Type of credentialSubject  # noqa: E501

        :param prop_type: The prop_type of this VcSchemaProperty.  # noqa: E501
        :type: str
        """
        if prop_type is None:
            raise ValueError("Invalid value for `prop_type`, must not be `None`")  # noqa: E501

        self._prop_type = prop_type

    @property
    def parent_object_index(self):
        """Gets the parent_object_index of this VcSchemaProperty.  # noqa: E501

        parent property  # noqa: E501

        :return: The parent_object_index of this VcSchemaProperty.  # noqa: E501
        :rtype: float
        """
        return self._parent_object_index

    @parent_object_index.setter
    def parent_object_index(self, parent_object_index):
        """Sets the parent_object_index of this VcSchemaProperty.

        parent property  # noqa: E501

        :param parent_object_index: The parent_object_index of this VcSchemaProperty.  # noqa: E501
        :type: float
        """
        if parent_object_index is None:
            raise ValueError("Invalid value for `parent_object_index`, must not be `None`")  # noqa: E501

        self._parent_object_index = parent_object_index

    @property
    def vc_schema(self):
        """Gets the vc_schema of this VcSchemaProperty.  # noqa: E501

        The VcSchema is origin  # noqa: E501

        :return: The vc_schema of this VcSchemaProperty.  # noqa: E501
        :rtype: AllOfVcSchemaPropertyVcSchema
        """
        return self._vc_schema

    @vc_schema.setter
    def vc_schema(self, vc_schema):
        """Sets the vc_schema of this VcSchemaProperty.

        The VcSchema is origin  # noqa: E501

        :param vc_schema: The vc_schema of this VcSchemaProperty.  # noqa: E501
        :type: AllOfVcSchemaPropertyVcSchema
        """

        self._vc_schema = vc_schema

    @property
    def created_at(self):
        """Gets the created_at of this VcSchemaProperty.  # noqa: E501

        The date the user was created  # noqa: E501

        :return: The created_at of this VcSchemaProperty.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this VcSchemaProperty.

        The date the user was created  # noqa: E501

        :param created_at: The created_at of this VcSchemaProperty.  # noqa: E501
        :type: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this VcSchemaProperty.  # noqa: E501

        The date the user was last updated  # noqa: E501

        :return: The updated_at of this VcSchemaProperty.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this VcSchemaProperty.

        The date the user was last updated  # noqa: E501

        :param updated_at: The updated_at of this VcSchemaProperty.  # noqa: E501
        :type: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VcSchemaProperty, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VcSchemaProperty):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
