# coding: utf-8

"""
    iDroit Dashboard Admin API

         これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)     # noqa: E501

    OpenAPI spec version: 0.9.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VerifyBadgeDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'veriify_vc': 'bool',
        'vp_info_id': 'str'
    }

    attribute_map = {
        'veriify_vc': 'veriifyVC',
        'vp_info_id': 'vpInfoId'
    }

    def __init__(self, veriify_vc=True, vp_info_id='false'):  # noqa: E501
        """VerifyBadgeDto - a model defined in Swagger"""  # noqa: E501
        self._veriify_vc = None
        self._vp_info_id = None
        self.discriminator = None
        if veriify_vc is not None:
            self.veriify_vc = veriify_vc
        self.vp_info_id = vp_info_id

    @property
    def veriify_vc(self):
        """Gets the veriify_vc of this VerifyBadgeDto.  # noqa: E501

        (任意) バッジに紐づいたVC情報を検証するか否か。`true`の場合VC情報をfalseの場合`vpInfoId`で指定されたVP情報を検証する  # noqa: E501

        :return: The veriify_vc of this VerifyBadgeDto.  # noqa: E501
        :rtype: bool
        """
        return self._veriify_vc

    @veriify_vc.setter
    def veriify_vc(self, veriify_vc):
        """Sets the veriify_vc of this VerifyBadgeDto.

        (任意) バッジに紐づいたVC情報を検証するか否か。`true`の場合VC情報をfalseの場合`vpInfoId`で指定されたVP情報を検証する  # noqa: E501

        :param veriify_vc: The veriify_vc of this VerifyBadgeDto.  # noqa: E501
        :type: bool
        """

        self._veriify_vc = veriify_vc

    @property
    def vp_info_id(self):
        """Gets the vp_info_id of this VerifyBadgeDto.  # noqa: E501

        (任意)   # noqa: E501

        :return: The vp_info_id of this VerifyBadgeDto.  # noqa: E501
        :rtype: str
        """
        return self._vp_info_id

    @vp_info_id.setter
    def vp_info_id(self, vp_info_id):
        """Sets the vp_info_id of this VerifyBadgeDto.

        (任意)   # noqa: E501

        :param vp_info_id: The vp_info_id of this VerifyBadgeDto.  # noqa: E501
        :type: str
        """
        if vp_info_id is None:
            raise ValueError("Invalid value for `vp_info_id`, must not be `None`")  # noqa: E501

        self._vp_info_id = vp_info_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VerifyBadgeDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VerifyBadgeDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
